version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./app/static:/app/app/static
      - ./migrations:/app/migrations
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    user: "1000:1000"
    restart: unless-stopped 