"""Add LLMConfig model

Revision ID: f63555df70fd
Revises: 
Create Date: 2024-12-19 15:33:43.194011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63555df70fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_url', sa.String(length=200), nullable=False),
    sa.Column('api_key', sa.String(length=200), nullable=False),
    sa.Column('selected_model', sa.String(length=100), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_config')
    # ### end Alembic commands ###
